<x-website-layout>
    <x-website.header.header/>
    <x-website.container>
        <x-website.main-title>
            Reservaciones
        </x-website.main-title>
        <livewire:appointment-reservation-livewire/>
    </x-website.container>
</x-website-layout>
